apiVersion: apps/v1
kind: Deployment
metadata:
  name: dna-callnotes
  labels:
    component: mse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dna-callnotes
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dna-callnotes
    spec:
      containers:
        - name: dna-callnotes
          image: omnipresenceacr.azurecr.io/indegene.io/dna-callnotes:BITBUCKET_COMMIT
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: environment-settings
          resources:
            limits:
              memory: 1Gi
            #            cpu: 500m
            requests:
              memory: 1Gi
          #            cpu: 150m
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: 5000
            timeoutSeconds: 30
      imagePullSecrets:
        - name: regcred2
---
apiVersion: v1
kind: Service
metadata:
  name: dna-callnotes-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 5000
  selector:
    app: dna-callnotes
  type: ClusterIP
